# Generated by Django 5.2.11 on 2026-02-05 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Producenci',
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.TextField(blank=True)),
                ('dostepny', models.BooleanField(default=True)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategoria')),
                ('producent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producent')),
            ],
            options={
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='Awaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_usterki', models.TextField()),
                ('data_zgloszenia', models.DateTimeField(auto_now_add=True)),
                ('czy_naprawione', models.BooleanField(default=False)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produkt')),
            ],
            options={
                'verbose_name_plural': 'Awarie',
            },
        ),
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wypozyczenia', models.DateField(auto_now_add=True)),
                ('data_zwrotu', models.DateField(blank=True, null=True)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produkt')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wypożyczenia',
            },
        ),
    ]
